import io
import os
from datetime import datetime
from typing import Any, Dict, List, Optional

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.util import Inches
from pptx.enum.shapes import MSO_SHAPE


class PPTXBuilder:
    def __init__(self, templates_dir: Optional[str] = None):
        base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        self.templates_dir = templates_dir or os.path.join(base_dir, "templates")
        self.template_path = os.path.join(self.templates_dir, "slide_template.pptx")

        if os.path.exists(self.template_path):
            self.prs = Presentation(self.template_path)
        else:
            os.makedirs(self.templates_dir, exist_ok=True)
            self.prs = Presentation()
            self.prs.save(self.template_path)

        # Force slide size.
        self.prs.slide_width = Inches(13.33)  # widescreen 16:9
        self.prs.slide_height = Inches(7.5)

        # Color scheme
        self.DARK_BLUE = RGBColor(0x1F, 0x38, 0x64)
        self.MID_BLUE = RGBColor(0x2E, 0x75, 0xB6)
        self.TEAL = RGBColor(0x0F, 0x6E, 0x56)
        self.RED = RGBColor(0xC0, 0x00, 0x00)
        self.GREEN = RGBColor(0x1E, 0x5C, 0x2E)
        self.LIGHT_BG = RGBColor(0xF2, 0xF2, 0xF2)

        self.report_date: str = datetime.now().strftime("%Y%m%d")

    def start_or_load_report(self, output_path: str):
        """
        Load an existing report for incremental updates, or create a new one.
        """
        if os.path.exists(output_path):
            self.prs = Presentation(output_path)
            self.prs.slide_width = Inches(13.33)
            self.prs.slide_height = Inches(7.5)
            return

        if os.path.exists(self.template_path):
            self.prs = Presentation(self.template_path)
        else:
            self.prs = Presentation()
        self.prs.slide_width = Inches(13.33)
        self.prs.slide_height = Inches(7.5)

    def _blank_slide_layout(self):
        # Choose a blank layout index if available; otherwise fallback to last layout.
        for i, layout in enumerate(self.prs.slide_layouts):
            if getattr(layout, "name", "") and "Blank" in layout.name:
                return i
        return len(self.prs.slide_layouts) - 1

    def _clear_slide(self, slide):
        for shape in list(slide.shapes):
            element = shape.element
            element.getparent().remove(element)

    def _get_slide_title_text(self, slide) -> str:
        for shape in slide.shapes:
            if not getattr(shape, "has_text_frame", False):
                continue
            text = (shape.text_frame.text or "").strip()
            if text:
                return text
        return ""

    def _find_group_slide(self, sheet_name: str):
        expected_prefix = f"{sheet_name}  |  Date:"
        for slide in self.prs.slides:
            for shape in slide.shapes:
                if not getattr(shape, "has_text_frame", False):
                    continue
                text = (shape.text_frame.text or "").strip()
                if text.startswith(expected_prefix):
                    return slide
        return None

    def add_title_slide(self, report_date: str, group_count: int):
        """
        Slide layout: blank.
        Title: "ITSM Weekly Report — {date}" (large, dark blue, centered)
        Subtitle: "Auto-generated | {n} groups | AI-powered insights"
        Footer: "Generated by ITSM Automation Agent | Confidential"
        Background: white with a dark blue bar at top (1 inch height)
        """

        self.report_date = report_date
        slide = self.prs.slides[0] if len(self.prs.slides) > 0 else self.prs.slides.add_slide(self.prs.slide_layouts[self._blank_slide_layout()])
        self._clear_slide(slide)

        # Top bar background.
        top_bar = slide.shapes.add_shape(
            MSO_SHAPE.RECTANGLE,
            Inches(0),
            Inches(0),
            self.prs.slide_width,
            Inches(1),
        )
        top_bar.fill.solid()
        top_bar.fill.fore_color.rgb = self.DARK_BLUE
        top_bar.line.fill.background()

        # Main title
        title_box = slide.shapes.add_textbox(Inches(0), Inches(1.1), self.prs.slide_width, Inches(1.0))
        tf = title_box.text_frame
        tf.clear()
        p = tf.paragraphs[0]
        p.text = f"ITSM Weekly Report — {report_date}"
        p.alignment = PP_ALIGN.CENTER
        p.font.size = Inches(0.35)
        p.font.bold = True
        p.font.color.rgb = self.DARK_BLUE

        # Subtitle
        subtitle_box = slide.shapes.add_textbox(Inches(0), Inches(2.0), self.prs.slide_width, Inches(0.6))
        tf2 = subtitle_box.text_frame
        tf2.clear()
        p2 = tf2.paragraphs[0]
        p2.text = f"Auto-generated | {group_count} groups | AI-powered insights"
        p2.alignment = PP_ALIGN.CENTER
        p2.font.size = Inches(0.18)
        p2.font.color.rgb = self.MID_BLUE

        # Footer
        footer_box = slide.shapes.add_textbox(Inches(0), Inches(6.9), self.prs.slide_width, Inches(0.4))
        tf3 = footer_box.text_frame
        tf3.clear()
        p3 = tf3.paragraphs[0]
        p3.text = "Generated by ITSM Automation Agent | Confidential"
        p3.alignment = PP_ALIGN.CENTER
        p3.font.size = Inches(0.13)
        p3.font.color.rgb = RGBColor(0x33, 0x33, 0x33)

    def _render_group_slide(
        self,
        slide,
        sheet_name: str,
        ai_output: Dict[str, Any],
        kpi_rows: List[Dict[str, Any]],
        chart_bytes: Optional[bytes],
    ):
        """
        SLIDE LAYOUT (widescreen, 13.33 x 7.5 inches):
        - Header bar (dark blue, 1 inch tall)
        - LEFT column: summary, KPI table, insights
        - RIGHT column: chart image if available else achievements
        """

        # Header bar
        top_bar = slide.shapes.add_shape(
            MSO_SHAPE.RECTANGLE,
            Inches(0),
            Inches(0),
            self.prs.slide_width,
            Inches(1),
        )
        top_bar.fill.solid()
        top_bar.fill.fore_color.rgb = self.DARK_BLUE
        top_bar.line.fill.background()

        header_text = slide.shapes.add_textbox(Inches(0.2), Inches(0.15), Inches(10), Inches(0.8))
        tf = header_text.text_frame
        tf.clear()
        p = tf.paragraphs[0]
        date_short = self.report_date
        p.text = f"{sheet_name}  |  Date: {date_short}"
        p.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
        p.font.size = Inches(0.20)
        p.font.bold = True

        # Layout constants
        left_x = Inches(0)
        right_x = Inches(6.5)
        left_w = Inches(6.5)
        right_w = Inches(13.33 - 6.5)

        summary_y = Inches(1.15)
        summary_h = Inches(1.2)
        table_y = summary_y + summary_h + Inches(0.05)
        insights_y = table_y + Inches(2.0)
        bottom_margin = Inches(0.2)

        # Summary box
        summary_bg = slide.shapes.add_shape(
            MSO_SHAPE.RECTANGLE,
            left_x,
            summary_y,
            left_w,
            summary_h,
        )
        summary_bg.fill.solid()
        summary_bg.fill.fore_color.rgb = self.LIGHT_BG
        summary_bg.line.color.rgb = self.LIGHT_BG

        summary_text = slide.shapes.add_textbox(left_x + Inches(0.2), summary_y + Inches(0.1), left_w - Inches(0.4), summary_h - Inches(0.2))
        tf_sum = summary_text.text_frame
        tf_sum.clear()
        tf_sum.word_wrap = True
        p_sum = tf_sum.paragraphs[0]
        p_sum.text = "Summary"
        p_sum.font.bold = True
        p_sum.font.color.rgb = self.DARK_BLUE
        p_sum.font.size = Inches(0.14)
        p_sum = tf_sum.add_paragraph()
        p_sum.text = ai_output.get("summary", "")
        p_sum.font.size = Inches(0.12)
        p_sum.font.color.rgb = RGBColor(0x33, 0x33, 0x33)

        # KPI table
        kpi_rows_safe = kpi_rows or []
        table_cols = 4
        table_row_count = max(1, len(kpi_rows_safe) + 1)
        table_box = slide.shapes.add_table(
            table_row_count,
            table_cols,
            left_x,
            table_y,
            left_w,
            Inches(2.0),
        )
        table = table_box.table

        # Header row
        headers = ["KPI Name", "Actual", "Target", "Status"]
        for col_idx in range(table_cols):
            cell = table.cell(0, col_idx)
            cell.text = headers[col_idx]
            for paragraph in cell.text_frame.paragraphs:
                paragraph.font.bold = True
                paragraph.font.color.rgb = self.DARK_BLUE

        # Data rows
        for i, row in enumerate(kpi_rows_safe, start=1):
            kpi_name = str(row.get("kpi_name", row.get("kpi", "")))
            actual = row.get("actual_value")
            threshold = row.get("threshold")
            status = row.get("status", "UNKNOWN")

            table.cell(i, 0).text = kpi_name
            table.cell(i, 1).text = "" if actual is None else str(actual)
            table.cell(i, 2).text = "" if threshold is None else str(threshold)
            status_cell = table.cell(i, 3)
            status_cell.text = status

            fill_color = self.GREEN if status == "PASS" else self.RED
            status_cell.fill.solid()
            status_cell.fill.fore_color.rgb = fill_color

            # Font color for status for contrast.
            for p in status_cell.text_frame.paragraphs:
                p.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)

        # Insights box
        insights_bg = slide.shapes.add_shape(
            MSO_SHAPE.RECTANGLE,
            left_x,
            insights_y,
            left_w,
            Inches(2.3),
        )
        insights_bg.fill.solid()
        insights_bg.fill.fore_color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
        insights_bg.line.color.rgb = self.TEAL
        insights_bg.line.width = 1

        insights_text = slide.shapes.add_textbox(
            left_x + Inches(0.2),
            insights_y + Inches(0.1),
            left_w - Inches(0.4),
            Inches(2.1),
        )
        tf_ins = insights_text.text_frame
        tf_ins.clear()
        p0 = tf_ins.paragraphs[0]
        p0.text = "Insights"
        p0.font.bold = True
        p0.font.color.rgb = self.DARK_BLUE

        insights = ai_output.get("insights") or []
        for line in insights:
            p_line = tf_ins.add_paragraph()
            p_line.text = str(line)
            p_line.font.italic = True
            p_line.font.size = Inches(0.12)
            p_line.font.color.rgb = self.DARK_BLUE

        # Right column content
        if chart_bytes:
            try:
                chart_stream = io.BytesIO(chart_bytes)
                # Insert chart image.
                slide.shapes.add_picture(
                    chart_stream,
                    right_x,
                    summary_y,
                    width=right_w,
                    height=Inches(4.2),
                )
            except Exception:
                # If chart insertion fails, fall back to achievements.
                chart_bytes = None

        if not chart_bytes:
            achievements_box = slide.shapes.add_shape(
                MSO_SHAPE.RECTANGLE,
                right_x,
                summary_y,
                right_w,
                Inches(2.5),
            )
            achievements_box.fill.solid()
            achievements_box.fill.fore_color.rgb = self.LIGHT_BG
            achievements_box.line.color.rgb = self.LIGHT_BG

            ach_text = slide.shapes.add_textbox(
                right_x + Inches(0.2),
                summary_y + Inches(0.1),
                right_w - Inches(0.4),
                Inches(2.3),
            )
            tf_ach = ach_text.text_frame
            tf_ach.clear()
            pA = tf_ach.paragraphs[0]
            pA.text = "Key Achievements"
            pA.font.bold = True
            pA.font.color.rgb = self.DARK_BLUE

            for ach in ai_output.get("key_achievements") or []:
                p_line = tf_ach.add_paragraph()
                p_line.text = f"• {ach}"
                p_line.font.size = Inches(0.12)
                p_line.font.color.rgb = RGBColor(0x33, 0x33, 0x33)

    def add_group_slide(
        self,
        sheet_name: str,
        ai_output: Dict[str, Any],
        kpi_rows: List[Dict[str, Any]],
        chart_bytes: Optional[bytes],
    ):
        existing = self._find_group_slide(sheet_name)
        if existing is None:
            slide = self.prs.slides.add_slide(self.prs.slide_layouts[self._blank_slide_layout()])
        else:
            slide = existing
            self._clear_slide(slide)
        self._render_group_slide(slide, sheet_name, ai_output, kpi_rows, chart_bytes)

    def save(self, output_path: str) -> str:
        """Save PPTX and return file path."""
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        self.prs.save(output_path)
        return output_path

